### ISSUE TITLE
Add/Update Unit tests

### ISSUE THREAD

**Issue by MichaelRoussel** [luluwheelan/Group7A2#5]

**Comment by luluwheelan** [comment]
Lulu is working on Unit Testing.

**Comment by luluwheelan** [comment]
Categories Controller unit test is done. Coverage is over 90%.
Still working on post and comment.

**Comment by luluwheelan** [comment]
PostsController unit test code coverage is over 80%.
Still working on comment controller.

**Comment by luluwheelan** [comment]
CommentController is done.
